version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/backend

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  BeforeInstall:
    - location: scripts/install.sh
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start.sh
  
  AfterInstall:
    - location: scripts/validate.sh
      runas: ec2-user
